### ISSUE TITLE
Easy way to update the version number

### ISSUE THREAD

**Issue by KFDing** [3D-e-Chem/tycho-knime-node-archetype#24]
Hi Stefan,

when I want to update the version for feature and p2, I have to manually find the names and modify them.  
Is there any way to change one set, and all related version will be updated?? And how??

Regards
Kefang

**Comment by sverhoeven** [comment]
The `New release` chapter in the generated README.md includes a command to do that.
The whole repo has one version, which will be updated by that command in all the files.

Command is `mvn org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=<version>-SNAPSHOT`

**Comment by KFDing** [comment]
Ach... didn't see it before. Thanks
